/// Flutter icons SpectrumIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpectrumIcons
///      fonts:
///       - asset: fonts/SpectrumIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SpectrumIcons {
  SpectrumIcons._();

  static const _kFontFam = 'SpectrumIcons';
  static const String? _kFontPkg = null;

  static const IconData weight_kilogram = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scale = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_register = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
